# Generated by Django 4.1.1 on 2023-01-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='cover',
            field=models.BooleanField(default=False, verbose_name='Gallery cover? True/False'),
        ),
    ]
