# Generated by Django 4.1.1 on 2023-01-23 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mfevents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infohome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(default='Headline', max_length=100, verbose_name='Headline')),
                ('info', models.TextField(default='Write Text Here!', verbose_name='Home information')),
                ('top', models.BooleanField(default=False, verbose_name='Top/welcome mesage (True/False)')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('edited_dt', models.DateTimeField(auto_now=True, verbose_name='Date edited')),
            ],
        ),
        migrations.CreateModel(
            name='LinkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=100, verbose_name='Link type name')),
                ('social', models.BooleanField(default=False, verbose_name='Social Media')),
                ('stream', models.BooleanField(default=False, verbose_name='Music Streaming')),
                ('radio', models.BooleanField(default=False, verbose_name='Radio')),
                ('records', models.BooleanField(default=False, verbose_name='Records')),
                ('ticket', models.BooleanField(default=False, verbose_name='Tickets')),
                ('tek', models.BooleanField(default=False, verbose_name='Technical Equipment')),
                ('merch', models.BooleanField(default=False, verbose_name='Merchandise')),
                ('culture', models.BooleanField(default=False, verbose_name='Culture')),
                ('other', models.BooleanField(default=False, verbose_name='Other links')),
            ],
        ),
        migrations.CreateModel(
            name='Photohome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Photo #', max_length=50, verbose_name='Photo name')),
                ('hm_image', models.ImageField(blank=True, null=True, upload_to='home_images/', verbose_name='Home page image')),
                ('portrait', models.BooleanField(default=False, verbose_name='Portrait? True/False')),
                ('upload_dt', models.DateTimeField(auto_now_add=True, verbose_name='Date Photo uploaded')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=100, verbose_name='Link name')),
                ('mflink', models.BooleanField(default=False, verbose_name='More Fire link')),
                ('mix_bol', models.BooleanField(default=False, verbose_name='Mix link')),
                ('track_bol', models.BooleanField(default=False, verbose_name='Track link')),
                ('link_url', models.URLField(verbose_name='Link url')),
                ('logo_lnk', models.ImageField(blank=True, null=True, upload_to='logo_images/', verbose_name='Link Logo')),
                ('linktype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.linktype')),
                ('mix', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mfevents.mix')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mfevents.track')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_bol', models.BooleanField(default=False, verbose_name='Event True/False')),
                ('mix_bol', models.BooleanField(default=False, verbose_name='Mix True/False')),
                ('track_bol', models.BooleanField(default=False, verbose_name='Track True/False')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Entrydate')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('edited_dt', models.DateTimeField(auto_now=True, verbose_name='Date edited')),
                ('event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mfevents.mfevent')),
                ('mix', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mfevents.mix')),
                ('track', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mfevents.track')),
            ],
        ),
    ]
