# Generated by Django 4.1.1 on 2023-02-23 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mfevents', '0001_initial'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infohome',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mfevents.mfevent'),
        ),
        migrations.AddField(
            model_name='infohome',
            name='mix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mfevents.mix'),
        ),
        migrations.AddField(
            model_name='infohome',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mfevents.track'),
        ),
        migrations.AlterField(
            model_name='link',
            name='mix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mfevents.mix'),
        ),
        migrations.AlterField(
            model_name='link',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mfevents.track'),
        ),
    ]
