# Generated by Django 4.1.1 on 2023-03-09 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_infohome_event_infohome_mix_infohome_track_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photohome',
        ),
    ]
