# Generated by Django 4.1.1 on 2023-01-23 17:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=120, verbose_name='Event Crew')),
                ('contact_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Contact name')),
                ('contact_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Contact phone number')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Contact email')),
                ('website', models.URLField(blank=True, null=True, verbose_name='website')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('edited_dt', models.DateTimeField(auto_now=True, verbose_name='Date edited')),
            ],
        ),
        migrations.CreateModel(
            name='EventEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('message', models.CharField(max_length=300, verbose_name='Message')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('edited_dt', models.DateTimeField(auto_now=True, verbose_name='Date edited')),
            ],
        ),
        migrations.CreateModel(
            name='MFEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Event name')),
                ('type', models.CharField(choices=[('Sound System', (('carnival_S', 'Carnival/Street Party'), ('club_S', 'Club '), ('club_S_sc', 'Club: Sound-Clash'), ('festival_S', 'Festival'))), ('DJ', (('radio', 'Radio show'), ('carnival_dj', 'Carnival/Street Party (DJ)'), ('club_dj', 'Club (DJ)'), ('club_dj_sc', 'Club (DJ): Sound-Clash'), ('festival_dj', 'Festival (DJ)'), ('pub_dj', 'Pub (DJ)'))), ('private', 'Private Event'), ('workshop', 'Workshop')], default='club_S', max_length=20, verbose_name='Type')),
                ('status', models.CharField(choices=[('Plan', 'Planning'), ('Scheduled', 'Scheduled'), ('Cancelled', 'Cancelled')], default='Plan', max_length=20, verbose_name='Status')),
                ('start_dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Event (start) time & date')),
                ('finish_dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Event (finish) time & date')),
                ('finished', models.BooleanField(default=False, verbose_name='Event Finished')),
                ('soundclash', models.BooleanField(default=False, verbose_name='Sounclash')),
                ('event_info', models.TextField(blank=True, null=True, verbose_name='Information')),
                ('event_image', models.ImageField(blank=True, null=True, upload_to='event_images/', verbose_name='Event Image')),
                ('event_url', models.URLField(blank=True, null=True, verbose_name='Event website')),
                ('ticket_url', models.URLField(blank=True, null=True, verbose_name='Ticket website')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('edited_dt', models.DateTimeField(auto_now=True, verbose_name='Date edited')),
                ('bands', models.ManyToManyField(related_name='event_bands', to='music.band')),
                ('genre', models.ManyToManyField(related_name='event_genre', to='music.genre')),
                ('instrumentals', models.ManyToManyField(limit_choices_to={'artist_type__instrumentalist': True}, related_name='event_instrumentals', to='music.artist')),
                ('organiser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_organiser', to='mfevents.eventcrew')),
                ('selectas', models.ManyToManyField(limit_choices_to={'artist_type__selecta': True}, related_name='event_selectas', to='music.artist')),
                ('soundsystem', models.ManyToManyField(related_name='event_soundsystem', to='music.soundsystem')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Venue name')),
                ('location', models.CharField(blank=True, max_length=250, null=True, verbose_name='Venue location')),
                ('postcode', models.CharField(blank=True, max_length=10, null=True, verbose_name='Venue postcode')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Venue website')),
                ('contact_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Venue contact')),
                ('contact_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Contact phone number')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Contact email')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('edited_dt', models.DateTimeField(auto_now=True, verbose_name='Date edited')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, verbose_name='Track Name')),
                ('recorded_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Track Recorded Date')),
                ('release_date', models.DateField(default=django.utils.timezone.now, verbose_name='Track Release Date')),
                ('track_embed', models.CharField(blank=True, max_length=500, null=True, verbose_name='Embed Track html')),
                ('track_info', models.TextField(blank=True, null=True, verbose_name='Information')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('edited_dt', models.DateTimeField(auto_now=True, verbose_name='Date edited')),
                ('band', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='music.band')),
                ('featured_artists', models.ManyToManyField(related_name='track_artists', to='music.artist')),
                ('genre', models.ManyToManyField(related_name='track_genre', to='music.genre')),
                ('label', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='music.label')),
                ('producer', models.ManyToManyField(related_name='track_producers', to='music.producer')),
                ('studio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='music.studio')),
            ],
        ),
        migrations.CreateModel(
            name='Mix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, verbose_name='Mix Name')),
                ('event_bol', models.BooleanField(default=False, verbose_name='Mix from Event yes/no')),
                ('recorded_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Mix Recorded Date')),
                ('release_date', models.DateField(default=django.utils.timezone.now, verbose_name='Mix Release Date')),
                ('mix_embed', models.CharField(blank=True, max_length=500, null=True, verbose_name='Embed mix html')),
                ('mix_info', models.TextField(blank=True, null=True, verbose_name='Information')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('edited_dt', models.DateTimeField(auto_now=True, verbose_name='Date edited')),
                ('dj', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='music.artist')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mfevents.mfevent')),
                ('featured_artists', models.ManyToManyField(related_name='mix_featured_artists', to='music.artist')),
                ('genre', models.ManyToManyField(related_name='mix_genre', to='music.genre')),
            ],
        ),
        migrations.AddField(
            model_name='mfevent',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mfevents.venue'),
        ),
        migrations.AddField(
            model_name='mfevent',
            name='vocals',
            field=models.ManyToManyField(limit_choices_to={'artist_type__vocalist': True}, related_name='event_vocals', to='music.artist'),
        ),
    ]
